### ISSUE TITLE
Strange translation?

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/menu-management-app#3]
@Markionium  @nicolayr 
https://github.com/dhis2/menu-management-app/blob/master/src/i18n/menu-management.properties#L5

looks very strange. Is this correct?

**Comment by nicolayr** [comment]
Yes, it's correct. Seems like @Markionium has been experimenting with a new way of doing translations ;)

**Comment by Markionium** [comment]
Closing this and making it part of this pull request https://github.com/dhis2/menu-management-app/pull/5
